name: Train NLP Model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run linter (optional but good)
      run: |
        pip install flake8
        flake8 script.py inference.py || true

    - name: Run training script (dry run)
      run: |
        echo "Running script.py — change to actual train trigger if needed"
        python script.py || true
